// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ExportTestCSV', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ExportTestCSV', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("radhi")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("1234")
    await driver.findElement(By.css(".dark-button")).click()
    await driver.findElement(By.css(".invoice > div")).click()
    await driver.findElement(By.css("tbody:nth-child(2) .ic_export")).click()
  })
})
