// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('linked_to_payment', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('linked_to_payment', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect({ width: 1552, height: 928 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("username")).sendKeys("test")
    await driver.findElement(By.id("password")).sendKeys("3200")
    await driver.findElement(By.css(".dark-button")).click()
    //await driver.findElement(By.css(".ic_notificaiton")).click()
    //await driver.findElement(By.css("strong:nth-child(2)")).click()
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.css("html")).click()
  })
})
