//final checked by ramita and radhi (11/08)
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SupplierSelenium.test.js', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SupplierSelenium.test.js', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect({ width: 960, height: 852 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("username")).sendKeys("test")
    await driver.findElement(By.id("password")).sendKeys("3200")
    await driver.findElement(By.css(".dark-button")).click()
    await driver.findElement(By.css(".supplier > div")).click()
    await driver.findElement(By.id("inp_search_blank")).click()
    await driver.findElement(By.id("inp_search_blank")).sendKeys("LEE")
    await driver.findElement(By.name("selectedRow")).click()
    await driver.findElement(By.id("nextButton")).click()
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.id("contact_number")).sendKeys("11223344")
    await driver.findElement(By.id("submit-button")).click()
    await driver.findElement(By.name("selectedRow")).click()
    await driver.findElement(By.id("nextButton")).click()
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.id("contact_number")).sendKeys("11223344")
    await driver.findElement(By.linkText("Back")).click()
  })
})
